# Generated by Django 2.2.1 on 2019-08-31 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apps_ids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=200)),
                ('client_Secrets', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('server_token', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('src_sys_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='auth_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentarn', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('planet', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=20)),
                ('clienttype', models.CharField(max_length=20)),
                ('clientidtype', models.CharField(max_length=20)),
                ('clientid', models.CharField(max_length=20)),
                ('knownfact', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('src_sys_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='List_mtd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('access_code', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=200)),
                ('vrn', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('src_sys_id', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='log1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(max_length=200)),
                ('status2', models.CharField(max_length=200)),
                ('status3', models.CharField(max_length=2000)),
                ('status4', models.CharField(max_length=2000)),
                ('status5', models.CharField(max_length=200)),
                ('status6', models.CharField(max_length=200)),
                ('src_sys_id', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='mtd_tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('access_code', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=200)),
                ('vrn', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('src_sys_id', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='pm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('asignee', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('epic', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=200)),
                ('estimation', models.CharField(max_length=20)),
                ('status2', models.CharField(max_length=200)),
                ('status3', models.CharField(max_length=200)),
                ('status4', models.CharField(max_length=200)),
                ('status5', models.CharField(max_length=200)),
                ('src_sys_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('asignee', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('epic', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=200)),
                ('estimation', models.CharField(max_length=20)),
                ('status2', models.CharField(max_length=200)),
                ('status3', models.CharField(max_length=200)),
                ('status4', models.CharField(max_length=200)),
                ('status5', models.CharField(max_length=200)),
                ('src_sys_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='posted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodKey', models.CharField(max_length=200)),
                ('vatDueSales', models.CharField(max_length=200)),
                ('vatDueAcquisitions', models.CharField(max_length=200)),
                ('vatReclaimedCurrPeriod', models.CharField(max_length=200)),
                ('netVatDue', models.CharField(max_length=200)),
                ('totalValueSalesExVAT', models.CharField(max_length=200)),
                ('totalValuePurchasesExVAT', models.CharField(max_length=200)),
                ('totalValueGoodsSuppliedExVAT', models.CharField(max_length=200)),
                ('totalAcquisitionsExVAT', models.CharField(max_length=200)),
                ('finalised', models.CharField(max_length=200)),
                ('vrn', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='testuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('vrn', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('userFullName', models.CharField(max_length=200)),
                ('emailAddress', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('src_sys_id', models.CharField(max_length=20)),
                ('appname', models.CharField(max_length=20)),
            ],
        ),
        
        
    ]
