# Generated by Django 2.2.1 on 2019-08-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref_num', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.CharField(default=None, max_length=200, null=True)),
                ('reference', models.CharField(default=None, max_length=200, null=True)),
                ('account', models.CharField(default=None, max_length=200, null=True)),
                ('client_name', models.CharField(default=None, max_length=200, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('invoice_version', models.CharField(default=None, max_length=255, null=True)),
                ('net', models.FloatField(default=0, null=True)),
                ('gross', models.FloatField(default=0, null=True)),
                ('vat', models.FloatField(default=0, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('unit_price', models.FloatField(default=0, null=True)),
                ('quantity', models.FloatField(default=0, null=True)),
                ('vat_rate', models.FloatField(default=0, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='payment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=None, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.invoice')),
            ],
        ),
    ]
